# Test rendering of the chart with the controller explicitly set to StatefulSet and autoscaling enabled.
# Test rendering of the chart with the controller explicitly set to DaemonSet.
controller:
  type: daemonset
  autoscaling:
    vertical:
      enabled: true
      resourcePolicy:
        containerPolicies:
          - containerName: alloy
            mode: Auto
            minAllowed:
              cpu: 100m
              memory: 100Mi
            maxAllowed:
              cpu: 1
              memory: 1Gi
